#!/usr/bin/env bash

#/ command: haproxy_exporter:create: "Create container image"
#/ usage: rerun haproxy_exporter:create  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --version <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES VERSION

. "$RERUN_MODULE_DIR/lib/functions.sh" "create" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------
THIS="$RERUN_MODULE_DIR/commands/create"
export NAME="haproxy_exporter-build"
export FROM="scratch"
export OPTS=""
. "$RERUN_MODULES/lib/buildah.sh"
. "$RERUN_MODULES/lib/print.sh"
PRINT "+H" "Downloading haproxy_exporter version $VERSION..."
TMPDIR=$(mktemp -d -p .)
1>/dev/null pushd "$TMPDIR"
    wget "https://github.com/prometheus/haproxy_exporter/releases/download/v${VERSION}/haproxy_exporter-${VERSION}.linux-amd64.tar.gz"
    tar -xf "haproxy_exporter-${VERSION}.linux-amd64.tar.gz"
    COPY "haproxy_exporter-${VERSION}.linux-amd64/haproxy_exporter" /
1>/dev/null popd
rm -rf "$TMPDIR"
ENTRYPOINT '["/haproxy_exporter", "--haproxy.scrape-uri=unix:/host/stats.sock"]'
COMMIT "$ARG"
exit 112
