#!/usr/bin/env bash

#/ command: haproxy:create: "Create container image"
#/ usage: rerun haproxy:create  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --config <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES CONFIG

. "$RERUN_MODULE_DIR/lib/functions.sh" "create" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
THIS="$RERUN_MODULE_DIR/commands/create"
export NAME="haproxy-build"
export FROM="docker://docker.io/library/debian:unstable-slim"
export OPTS=""
. "$RERUN_MODULES/lib/buildah.sh"
. "$RERUN_MODULES/lib/print.sh"
APT_GET="/usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -qq"
MKDIR /usr/share/man/man1
MKDIR /usr/share/man/man7
RUN /usr/bin/touch /usr/share/man/man1/sh.distrib.1.gz
RUN cp --remove-destination /usr/share/zoneinfo/UTC /etc/localtime
RUN $APT_GET update
RUN $APT_GET dist-upgrade
RUN $APT_GET install haproxy
RUN /usr/bin/find {/bin,/sbin,/usr/bin,/usr/sbin} -type f -exec chmod u-s {} +
CLEAR /tmp
CLEAR /var/tmp
CLEAR /var/cache
CLEAR /var/log
CLEAR /var/lib/apt/lists
CLEAR /usr/share/man
CLEAR /usr/share/common-licenses
CLEAR /usr/share/doc
RUN $APT_GET --allow-remove-essential remove sysvinit-utils e2fsprogs e2fslibs tzdata findutils dmeventd
RUN $APT_GET autoremove
RUN $APT_GET clean
RUN rm -rf /etc/haproxy
COPY "$CONFIG" /etc/haproxy
RUN chown -R haproxy:haproxy /etc/haproxy
ENTRYPOINT '["/usr/sbin/haproxy", "-W", "-f", "/etc/haproxy/haproxy.cfg"]'
COMMIT "$ARG"
exit 112
